#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba32f, binding = 0) uniform readonly image2D imgInput;
layout(rgba16f, binding = 1) uniform writeonly image2D imgOutput;

uniform vec2 u_resolution;
uniform int u_clampEnabled;

void main()
{
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    if (uv.x >= int(u_resolution.x) || uv.y >= int(u_resolution.y)) {return;}

    vec4 centerData = imageLoad(imgInput, uv);
    vec3 center = centerData.rgb;

    vec3 sum = vec3(0.0);
    vec3 neighborMax = vec3(0.0);
    int n = 0;
    
    for (int dy = -1; dy <= 1; dy++)
    for (int dx = -1; dx <= 1; dx++)
    {
        if (dx == 0 && dy == 0) {continue;}

        ivec2 p = uv + ivec2(dx, dy);
        if (p.x < 0 || p.y < 0 || p.x >= int(u_resolution.x) || p.y >= int(u_resolution.y)) {continue;}

        vec3 c = imageLoad(imgInput, p).rgb;
        sum += c;
        neighborMax = max(neighborMax, c);
        n++;
    }

    vec3 neihgborAvg = sum / max(n, 1);

    float lumCenter = dot(center, vec3(0.299, 0.587, 0.114));
    float lumNeighborMax = dot(neighborMax, vec3(0.299, 0.587, 0.115));

    const float clampFactor = 2.0;
    vec3 result = center;
    //bool wasClamped = false;

    if (u_clampEnabled == 1 && lumCenter > lumNeighborMax * clampFactor && lumNeighborMax > 1e-4)
    {
        result = mix(center, neihgborAvg, 0.9);
        //wasClamped = true;
    }

    //if (wasClamped)
    //{
    //    result = vec3(1.0, 0.0, 1.0);
    //}

    imageStore(imgOutput, uv, vec4(result, centerData.a));
}