#version 460 core

#define MAX_BOUNCES  7
#define SAMPLES_PER_PIXEL 1

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D img_output;
layout(rgba32f, binding = 1) uniform image2D img_normals;

struct Sphere 
{
    vec3 pos;
    float radius;
    int materialIndex;
    float padding[3];
};

struct Material
{
    vec3 color;
    float visibility;
    float roughness;
    float metallic;
    float emission;
    float opacity;
};

struct Vertex 
{
    vec3 pos;
    float pad;
    vec3 normal;
    float pad2;
};

struct BVHNode
{
    vec3 aabbMin;
    uint leftFirst;
    vec3 aabbMax;
    uint triCount;
};

struct hitResult
{
    float t;
    float baryU;
    float baryV;
};

const float M_PI = 3.1415926;

layout(std430, binding = 0) buffer SceneData {Sphere spheres[];};
layout(std430, binding = 1) buffer MaterialData {Material materials[];};
layout(std430, binding = 2) buffer VertexData {Vertex vertices[];};
layout(std430, binding = 3) buffer IndexData {uint indices[];};
layout(std430, binding = 4) buffer BVHData {BVHNode bvhNodes[];};
layout(std430, binding = 5) buffer TriangleMaterialData {uint triangleMaterials[];};

uniform vec2 u_resolution;
uniform int u_frameCount;
uniform sampler2D u_historyTexture;
uniform vec3 u_cameraPos;
uniform float u_cameraYaw;
uniform float u_cameraPitch;
uniform int u_timeOfDay;
uniform int u_skyEnabled;
uniform int u_smoothShading;
uniform int u_debugMode;
uniform int u_renderBothSides;
uniform float u_sunStrength;
uniform int u_nee;

uniform vec3 u_camForward;
uniform vec3 u_camRight;
uniform vec3 u_camUp;

uint pcgHash(inout uint state)
{
    state = state * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^state) * 277803737u;
    return (word >> 22u) ^ word;
}

float random(inout uint state)
{
    return float(pcgHash(state) * 2.3283064365386963e-10);
}

vec3 cosHemisphere(vec3 n, inout uint seed)
{
    float r1 = random(seed);
    float r2 = random(seed);

    float phi = 2.0 * M_PI * r1;
    float cosTheta = sqrt(1.0 - r2);
    float sinTheta = sqrt(r2);

    vec3 localRay = vec3(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta);
    
    vec3 up = abs(n.z) < 0.999 ? vec3(0, 0, 1) : vec3(1, 0, 0);
    vec3 tangent = normalize(cross(up, n));
    vec3 biTangent = cross(n, tangent);

    return tangent * localRay.x + biTangent * localRay.y + n * localRay.z;
}

float hitAABB(vec3 aabbMin, vec3 aabbMax, vec3 ro, vec3 invDir)
{
    
    vec3 t0s = (aabbMin - ro) * invDir;
    vec3 t1s = (aabbMax - ro) * invDir;

    vec3 tMin = min(t0s, t1s);
    vec3 tMax = max(t0s, t1s);

    float tNear = max(tMin.x, max(tMin.y, tMin.z));
    float tFar = min(tMax.x, min(tMax.y, tMax.z));

    return (tFar >= tNear && tFar > 0.0) ? max(0.0, tNear) : 1e30;
}

hitResult hitTriangleIndexed(int triIndex, vec3 ro, vec3 rd)
{
    uint i0 = indices[3 * triIndex + 0];
    uint i1 = indices[3 * triIndex + 1];
    uint i2 = indices[3 * triIndex + 2];

    vec3 v0 = vertices[i0].pos;
    vec3 v1 = vertices[i1].pos;
    vec3 v2 = vertices[i2].pos;

    vec3 edge1 = v1 - v0;
    vec3 edge2 = v2 - v0;
    vec3 h = cross(rd, edge2);
    float a = dot(edge1, h);

    if (u_renderBothSides == 0) {if (a < 0.0001) {return hitResult(-1.0, 0.0, 0.0);}}
    else {if (abs(a) < 0.0001) {return hitResult(-1.0, 0.0, 0.0);}}

    float f = 1.0 / a;
    vec3 s = ro - v0;
    float u = f * dot(s, h);

    if (u < 0.0 || u > 1.0) {return hitResult(-1.0, 0.0, 0.0);}

    vec3 q = cross(s, edge1);
    float v = f * dot(rd, q);

    if (v < 0.0 || u + v > 1.0) {return hitResult(-1.0, 0.0, 0.0);}

    float t = f * dot(edge2, q);

    if (t > 0.001) {return hitResult(t, u, v);};
    return hitResult(-1.0, 0.0, 0.0);
}

float hitSphere(Sphere s, vec3 ro, vec3 rd)
{
    vec3 oc = ro - s.pos;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - s.radius * s.radius;
    float h = b * b - c; 

    return (h < 0.0) ? -1.0 : (-b - sqrt(h));
}

void findClosestHit(vec3 ro, vec3 rd, vec3 invDir, bool primaryRay, 
                    out float minT, out int hitIndex, out int hitType,
                    out float baryU, out float baryV)
{
    minT = 10000.0;
    hitIndex = -1;
    hitType = 0;
    baryU = 0.0;
    baryV = 0.0;

    // Check for sphere
    for(int i = 0; i < spheres.length(); i++)
    {
        float t = hitSphere(spheres[i], ro , rd);
        if (t > 0.001 && t < minT)
        {
            bool invisible = materials[spheres[i].materialIndex].visibility > 0.5;

            // Skip if material is invisible
            if (primaryRay && invisible) {continue;}

            minT = t;
            hitIndex = i;
            hitType = 1;
        }
    }

    // Triangle
    int stack[64];
    int stackPtr = 0;   
    stack[stackPtr++] = 0;

    while (stackPtr > 0)
    {
        // Pop next node
        int nodeIdx = stack[--stackPtr];
        BVHNode node = bvhNodes[nodeIdx];

        // Skip if further than current best hit
        float distToBox = hitAABB(node.aabbMin, node.aabbMax, ro, invDir);
        if (distToBox >= minT) {continue;}

        if (node.triCount > 0)
        {
            for (uint i = 0; i < node.triCount; i++)
            {
                int triIdx = int(node.leftFirst + i);
                hitResult hitRes = hitTriangleIndexed(triIdx, ro, rd);

                if (hitRes.t > 0.001 && hitRes.t < minT)
                {
                    minT = hitRes.t;
                    hitIndex = triIdx;
                    hitType = 2;
                    baryU = hitRes.baryU;
                    baryV = hitRes.baryV;
                }
            }
        }
        else // Internal node
        {
            int leftChild = int(node.leftFirst);
            int rightChild = int(node.leftFirst + 1);

            float distL = hitAABB(bvhNodes[leftChild].aabbMin, bvhNodes[leftChild].aabbMax, ro, invDir);
            float distR = hitAABB(bvhNodes[rightChild].aabbMin, bvhNodes[rightChild].aabbMax, ro, invDir);

            if (distL < distR)
            {
                if (distR < minT) {stack[stackPtr++] = rightChild;}
                if (distL < minT) {stack[stackPtr++] = leftChild;}
            }
            else
            {
                if (distL < minT) {stack[stackPtr++] = leftChild;}
                if (distR < minT) {stack[stackPtr++] = rightChild;}
            }
        }
    }
}

void getSunPos(out vec3 sunDir, out vec3 sunColor)
{
    float sunAngle = (u_timeOfDay - 360.0) / 1440.0 * 6.283185;
    sunDir = normalize(vec3(cos(sunAngle), sin(sunAngle), 0.2));
    float sunAlt = sunDir.y;

    float dayF = smoothstep(0.05, 0.3, sunAlt);
    float nightF = smoothstep(0.0, -0.2, sunAlt);

    vec3 daySunColor = vec3(10.0, 8.0, 5.0);
    vec3 setSunColor = vec3(30.0, 10.0, 2.0);

    sunColor = mix(mix(setSunColor, vec3(0.0), nightF), daySunColor, dayF) * 2.0;
}

bool castShadowRay(vec3 ro, vec3 rd)
{
    vec3 invDir = 1.0 / rd;

    // Spheres
    for (int i = 0; i < spheres.length(); i++)
    {
        if (materials[spheres[i].materialIndex].visibility > 0.5) {continue;}

        float t = hitSphere(spheres[i], ro, rd);
        if (t > 0.001 && materials[spheres[i].materialIndex].opacity > 0.5) {return true;}
    }

    // Triangles
    int stack[64];
    int stackPtr = 0;
    stack[stackPtr++] = 0;

    while (stackPtr > 0)
    {
        int nodeIdx = stack[--stackPtr];
        BVHNode node = bvhNodes[nodeIdx];

        if (hitAABB(node.aabbMin, node.aabbMax, ro, invDir) >= 1e30) {continue;}

        if (node.triCount > 0)
        {
            for (uint i = 0; i < node.triCount; i++)
            {
                int triIdx = int(node.leftFirst + i);
                uint matIdx = triangleMaterials[triIdx];

                if (materials[matIdx].opacity > 0.5)
                {
                    hitResult hr = hitTriangleIndexed(triIdx, ro, rd);
                    if (hr.t > 0.001) {return true;}
                }
            }
        }
        else
        {
            int left = int(node.leftFirst);
            int right = int(node.leftFirst + 1);

            float dL = hitAABB(bvhNodes[left].aabbMin, bvhNodes[left].aabbMax, ro, invDir);
            float dR = hitAABB(bvhNodes[right].aabbMin, bvhNodes[right].aabbMax, ro, invDir);

            if (dL < dR)
            {
                if (dR < 1e30) {stack[stackPtr++] = right;}
                if (dL < 1e30) {stack[stackPtr++] = left;}
            }
            else
            {
                if (dL < 1e30) {stack[stackPtr++] = left;}
                if (dR < 1e30) {stack[stackPtr++] = right;}
            }
        }
    }
    return false;
}

void main()
{
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

    if (pixelCoord.x >= int(u_resolution.x) || pixelCoord.y >= int(u_resolution.y)) {return;}

    uint seed = uint(pixelCoord.x) + uint(pixelCoord.y) * uint(u_resolution.x) + uint(u_frameCount) * 7125413u;

    // Camera
    float aspect = u_resolution.x / u_resolution.y;

    vec3 ro = u_cameraPos;

    float fov = 45.0;
    float tanFov = tan(radians(fov) * 0.5);

    const int maxBounces = MAX_BOUNCES;
    const int samplesPerPixel = SAMPLES_PER_PIXEL;

    // Recursive raytracing
    vec3 frameColor = vec3(0.0, 0.0, 0.0);
    vec4 firstNormal = vec4(0.0);
    float firstRoughness = 1.0;

    for (int s = 0; s < samplesPerPixel; s++)
    {
        uint sampleSeed = seed + uint(s) * 9781u;

        //vec2 uv = (vec2(pixelCoord) + 0.5) / u_resolution * 2.0 - 1.0;
        vec2 uv = (vec2(pixelCoord) + vec2(random(sampleSeed), random(sampleSeed))) / u_resolution * 2.0 -1.0;
        uv.x *= aspect;

        vec3 rd = normalize(u_camForward + uv.x * tanFov * u_camRight + uv.y * tanFov * u_camUp);

        vec3 accumulatedLight = vec3(0.0, 0.0, 0.0);
        vec3 throughput = vec3(1.0, 1.0, 1.0);
        vec3 currentRo = u_cameraPos;
        vec3 currentRd = rd;

        for (int bounce = 0; bounce < maxBounces; bounce++)
        {
            float minT;
            int hitIndex;
            int hitType;
            float baryU;
            float baryV;
            bool firstHit = false;

            vec3 invDir = 1.0 / currentRd;
            findClosestHit(currentRo, currentRd, invDir, (bounce == 0), minT, hitIndex, hitType, baryU, baryV);

            if (bounce == 0 && hitIndex != -1) {firstHit = true;}

            if (hitIndex != -1)
            {
                vec3 hitPos = currentRo + currentRd * minT;
                vec3 normal;
                vec3 geometricNormal;
                int materialIndex;

                if (hitType == 1)
                {
                    Sphere s = spheres[hitIndex];
                    normal = normalize(hitPos - s.pos);
                    materialIndex = s.materialIndex;
                }
                else if (hitType == 2)
                {
                    uint i0 = indices[3 * hitIndex + 0];
                    uint i1 = indices[3 * hitIndex + 1];
                    uint i2 = indices[3 * hitIndex + 2];

                    vec3 v0 = vertices[i0].pos;
                    vec3 v1 = vertices[i1].pos;
                    vec3 v2 = vertices[i2].pos;

                    vec3 edge1 = v1 - v0;
                    vec3 edge2 = v2 - v0;

                    geometricNormal = normalize(cross(edge1, edge2));

                    if (u_smoothShading == 1)
                    {
                        float w = 1.0 - baryU - baryV;

                        normal = normalize(vertices[i0].normal * w +
                                           vertices[i1].normal * baryU +
                                           vertices[i2].normal * baryV);
                    }
                    else {normal = geometricNormal;}
                    
                    materialIndex = int(triangleMaterials[hitIndex]);
                }
                
                Material material = materials[materialIndex];
                accumulatedLight += material.color.rgb * material.emission * throughput;

                vec3 refNormal = (hitType == 2) ? geometricNormal : normal;
                bool isInside = dot(refNormal, currentRd) > 0.0;

                if(isInside) 
                {
                    normal = -normal;

                    vec3 absoption = (vec3(1.0) - material.color.rgb) * 2.0;
                    throughput *= exp(-absoption * minT);
                }

                if (random(sampleSeed) > material.opacity)
                {   
                    float baseIOR = 1.5;
                    float dispersion = 0.012;

                    float randColor = random(sampleSeed);
                    float channelIOR = baseIOR;
                    vec3 colorMask = vec3(1.0);

                    if (randColor < 0.333)
                    {
                        channelIOR = baseIOR - dispersion;
                        colorMask = vec3(3.0, 0.0, 0.0);
                    }
                    else if (randColor < 0.666)
                    {
                        channelIOR = baseIOR;
                        colorMask = vec3(0.0, 3.0, 0.0);
                    }
                    else
                    {
                        channelIOR = baseIOR + dispersion;
                        colorMask = vec3(0.0, 0.0, 3.0);
                    }

                    float eta = isInside ? channelIOR : (1 / channelIOR);

                    float f0 = (1 - channelIOR) / (1 + channelIOR);
                    float r0 = f0 * f0;
                    float rTheta = r0 + (1 - r0) * pow(1 - max(dot(normal, -currentRd), 0.0), 5.0);

                    if (rTheta > random(sampleSeed))
                    {
                        currentRd = reflect(currentRd, normal);
                        currentRo = hitPos + normal * 0.001;
                    }
                    else
                    {
                        vec3 refractDir = refract(currentRd, normal, eta);

                        if (length(refractDir) < 0.001)
                        {
                            currentRd = reflect(currentRd, normal);
                            currentRo = hitPos + normal * 0.001;
                        }
                        else
                        {
                            currentRd = normalize(mix(refractDir, cosHemisphere(-normal, sampleSeed), material.roughness * material.roughness));
                            currentRo = hitPos - normal * 0.001;

                            throughput *= colorMask;
                        }
                    }
                }
                else
                {
                    float fresnel = 0.04 + (1.0 - 0.04) * pow(1.0 - max(dot(normal, -currentRd), 0.0), 5.0);

                    if (u_skyEnabled == 1 && u_nee == 1)
                    {
                        vec3 sunDir, sunColor;
                        getSunPos(sunDir, sunColor);

                        const float sunCosMax = 0.9998;
                        const float sunSolidAngle = 2.0 * M_PI * (1.0 - sunCosMax);

                        float r1 = random(sampleSeed);
                        float r2 = random(sampleSeed);

                        float cosT = 1.0 - r1 * (1.0 - sunCosMax);
                        float sinT = sqrt(max(0.0, 1.0 - cosT * cosT));
                        float phi = 2.0 * M_PI * r2;

                        vec3 sunUp = abs(sunDir.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
                        vec3 sunTan = normalize(cross(sunUp, sunDir));
                        vec3 sunBit = cross(sunDir, sunTan);
                        vec3 shadowDir = normalize(sunTan * (cos(phi) * sinT) + sunBit * (sin(phi) * sinT) + sunDir * cosT);

                        float NdL = max(dot(normal, shadowDir), 0.0);

                        if (NdL > 0.0 && !castShadowRay(hitPos + normal * 0.001, shadowDir))
                        {
                            float diffuseWeight = 1.0 - mix(fresnel, 1.0, material.metallic);

                            accumulatedLight += throughput * (material.color.rgb / M_PI) * sunColor * (NdL * sunSolidAngle * diffuseWeight * u_sunStrength);
                        }
                    }

                    bool isSpecular = random(sampleSeed) < mix(fresnel, 1.0, material.metallic);

                    if (isSpecular)
                    {
                        vec3 reflectDir = reflect(currentRd, normal);

                        currentRd = normalize(mix(reflectDir, cosHemisphere(normal, sampleSeed), material.roughness * material.roughness));
                        throughput *= mix(vec3(1.0, 1.0, 1.0), material.color.rgb, material.metallic);
                    }
                    else
                    {
                        currentRd = cosHemisphere(normal, sampleSeed);
                        throughput *= material.color.rgb;
                    }

                    currentRo = hitPos + normal * 0.001;
                }

                if (firstHit) 
                {
                    firstNormal = vec4(normal * 0.5 + 0.5, minT);
                    firstRoughness = materials[materialIndex].roughness;    
                }
                
                if (bounce > 2)
                {
                    // Russian roulette
                    float p = max(throughput.r, max(throughput.g, throughput.b));
                    p = min(p, 1.0);
    
                    if (random(sampleSeed) > p) {break;}
                    throughput /= p;
                }
            }
            else
            {
                vec3 skyColor = vec3(0.0);
                float t = clamp(currentRd.y, -1.0, 1.0);

                float sunAngle = (u_timeOfDay - 360.0) / 1440.0 * 6.283185;
                vec3 sunDir = normalize(vec3(cos(sunAngle), sin(sunAngle), 0.2));

                float sunAlt = sunDir.y;

                float dayFactor = smoothstep(0.05, 0.3, sunAlt); 
                float nightFactor = smoothstep(0.0, -0.2, sunAlt);
                float sunsetFactor = 1.0 - smoothstep(0.0, 0.15, abs(sunAlt));

                vec3 dayTop = vec3(0.2, 0.4, 0.8);    vec3 dayMid = vec3(0.4, 0.6, 0.9);   vec3 dayBot = vec3(0.1, 0.1, 0.15);
                vec3 setTop = vec3(0.02, 0.02, 0.1);  vec3 setMid = vec3(0.6, 0.2, 0.05);  vec3 setBot = vec3(0.2, 0.05, 0.0);
                vec3 nightTop= vec3(0.01, 0.01, 0.05);vec3 nightMid = vec3(0.02, 0.02, 0.08);vec3 nightBot = vec3(0.0, 0.0, 0.02);

                vec3 daySunColor = vec3(10.0, 8.0, 5.0);
                vec3 setSunColor = vec3(30.0, 10.0, 2.0);

                vec3 top    = mix(mix(setTop, nightTop, nightFactor), dayTop, dayFactor);
                vec3 middle = mix(mix(setMid, nightMid, nightFactor), dayMid, dayFactor);
                vec3 bottom = mix(mix(setBot, nightBot, nightFactor), dayBot, dayFactor);
                vec3 sunColor = mix(mix(setSunColor, vec3(0.0), nightFactor), daySunColor, dayFactor);

                skyColor = mix(
                    mix(middle, top, smoothstep(0.0, 1.0, t)),
                    bottom,
                    smoothstep(0.0, 1.0, -t)
                );

                float sunDot = dot(currentRd, sunDir);
                float sunDiameter = 0.9998;

                float directionalGlow = max(sunDot, 0.0);
                float horizonGlow = exp(-abs(t) * 5.0) * sunsetFactor * (0.1 + 0.9 * directionalGlow);

                skyColor += horizonGlow * vec3(1.0, 0.5, 0.2);

                if (sunDot > sunDiameter) 
                { 
                    skyColor += sunColor * 2.0; 
                } 
                else if (sunDot > 0.0) 
                {
                    float halo = pow(sunDot, 256.0);
                    skyColor += sunColor * halo * 0.1 * (1.0 - nightFactor); 
                }

                float skyIntensity = smoothstep(-0.2, 0.2, sunAlt); 
                skyColor *= mix(0.4, 1.0, skyIntensity);

                if (u_skyEnabled == 0) {skyColor = vec3(0.0, 0.0, 0.0);}

                accumulatedLight += throughput * skyColor;
                break;
            }
        }
        float maxIntensity = 100.0;
        accumulatedLight = min(accumulatedLight, vec3(maxIntensity));

        if (u_debugMode == 0) {frameColor += accumulatedLight;}
        else {frameColor = firstNormal.rgb;}
    }
    
    frameColor /= float(samplesPerPixel);

    vec2 texUV = (vec2(pixelCoord) + 0.5) / u_resolution; 
    vec3 prevColor = texture(u_historyTexture, texUV).rgb;
    
    float weight = 1.0 / float(u_frameCount);

    if (u_frameCount > 4)
    {
        float lum = dot(frameColor, vec3(0.299, 0.587, 0.114));
        float prevLum = dot(prevColor, vec3(0.299, 0.587, 0.114));
        float maxAllowed = prevLum * 4.0 + 0.5; 
        if (lum > maxAllowed) {frameColor *= maxAllowed / lum;}
    }
    
    vec3 finalLinear = mix(prevColor, frameColor, weight);

    //imageStore(img_output, pixelCoord, vec4(firstNormal.rgb, 1.0));
    imageStore(img_output, pixelCoord, vec4(finalLinear, firstRoughness));
    imageStore(img_normals, pixelCoord, firstNormal);
}